events {}

http {

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    upstream api {
        server api:3000;
    }

    server {

        listen 80;

        server_name localhost;

        #
        # HEALTH & METRICS
        #
        location /health {

            proxy_pass http://api;

            proxy_http_version 1.1;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /metrics {

            proxy_pass http://api;

            proxy_http_version 1.1;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }

        #
        # API RATE LIMITED
        #
        location /api {

            limit_req zone=api_limit burst=20 nodelay;

            proxy_pass http://api;

            proxy_http_version 1.1;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}